DROP TABLE IF EXISTS USUARIOS;


CREATE TABLE USUARIOS (
   ID INT AUTO_INCREMENT PRIMARY KEY,
   NOME VARCHAR(50) NOT NULL,
   SOBRENOME VARCHAR(50) NOT NULL,
   CPF VARCHAR(14) NOT NULL,
   DATA_NASCIMENTO DATE NOT NULL,
   EMAIL VARCHAR(100) NOT NULL,
   SENHA VARCHAR(50) NOT NULL
);